---
- name: Configlet upload management
  hosts: cvaas
  connection: local
  gather_facts: false

  tasks:
    - name: Import Global CVaaS Vars
      ansible.builtin.include_vars:
        file: "../../../global_vars/DEMO_CVAAS.yml"

    - name: Uploading configlets to CVaaS
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'ENGINEERING_FABRIC'
        configlets_prefix: 'ENGINEERING_'
        state: present
        cv_collection: v3
        execute_tasks: false
