---

- name: Collect commands
  hosts: BACKBONE_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:

    - name: Collect commands
      import_role:
        name: eos_snapshot
