version: "3.9"
services:
  demo-dev06:
    build: .
    image: "demo-dev06:latest"
    container_name: demo-dev06
    # restart: always
    restart: no
    command: ['tail', '-f', '/dev/null']
    network_mode: "host"

    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
      - LC_ALL=UTF-8
    volumes:
      - ../:/workspace
