---

# FINANCE config file
#############################################
#                 L3 Leafs                  #
#############################################
l3leaf:
  defaults:
    platform: 7050SX3
    mlag_peer_ipv4_pool: 10.252.9.0/31
    mlag_peer_l3_ipv4_pool: 10.252.9.2/31
    loopback_ipv4_pool: 10.252.9.64/26
    loopback_ipv4_offset: 2 # Match number of spine switches
    vtep_loopback_ipv4_pool: 10.252.9.128/26
    virtual_router_mac_address: aa:aa:bb:bb:cc:cc
    spanning_tree_priority: 8192
    spanning_tree_mode: rapid-pvst
    evpn_gateway:
      remote_peers:
        - hostname: "BACKBONE-M11-CR1 Loopback"
          ip_address: 10.252.0.3
          bgp_as: 65000.1
        - hostname: "BACKBONE-M12-CR1 Loopback"
          ip_address: 10.252.0.4
          bgp_as: 65000.1

  node_groups:
#############################################
#   FINANCE BDF
#############################################
    - group: FINANCE_L3_LEAF1
      bgp_as: 65000.999
      filter:
        tags: [ALL_SWITCHES, FINANCE]
        tenants: [TENANT1]
      nodes:
        - name: FINANCE-BDF-DS1
          id: 1
          mgmt_ip: 10.252.15.101/24

        - name: FINANCE-BDF-DS2
          id: 2
          mgmt_ip: 10.252.15.102/24

#############################################
#                 L2 Leafs                  #
#############################################
l2leaf:
  defaults:
    platform: 720XP
    spanning_tree_mode: rapid-pvst
    mlag_peer_ipv4_pool: 10.252.9.0/31
    inband_mgmt_vlan: 4092
    inband_mgmt_vlan_name: INBAND_MGMT
    inband_mgmt_description: INBAND_MGMT
    inband_mgmt_subnet: 10.252.9.192/26
    inband_mgmt_gateway: 10.252.9.193
    structured_config:
      switchport_default:
        phone:
          vlan: "132"

  node_groups:
#############################################
# FINANCE TX1
#############################################
    - group: FINANCE_L2_TX1
      uplink_switches: ['FINANCE-BDF-DS1', 'FINANCE-BDF-DS2']
      filter:
        tags: [ALL_SWITCHES, FINANCE]
        tenants: [TENANT1]
      mlag: false

      nodes:
        - name: FINANCE-TX1-ES1
          id: 3
          mgmt_ip: 10.252.15.201/24
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1

        - name: FINANCE-TX1-ES2
          id: 4
          mgmt_ip: 10.252.15.202/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2

        - name: FINANCE-TX1-ES3
          id: 5
          mgmt_ip: 10.252.15.203/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3

        - name: FINANCE-TX1-ES4
          id: 6
          mgmt_ip: 10.252.15.204/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4

#############################################
#     FINANCE TX2
#############################################
    - group: FINANCE_L2_TX2
      uplink_switches: ['FINANCE-BDF-DS1', 'FINANCE-BDF-DS2']
      filter:
        tags: [ALL_SWITCHES, FINANCE]
        tenants: [TENANT1]
      mlag: false

      nodes:
        - name: FINANCE-TX2-ES1
          id: 7
          mgmt_ip: 10.252.15.205/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5

        - name: FINANCE-TX2-ES2
          id: 8
          mgmt_ip: 10.252.15.206/24
          uplink_switch_interfaces:
            - Ethernet6
            - Ethernet6

        - name: FINANCE-TX2-ES3
          id: 9
          mgmt_ip: 10.252.15.207/24
          uplink_switch_interfaces:
            - Ethernet7
            - Ethernet7

        - name: FINANCE-TX2-ES4
          id: 10
          mgmt_ip: 10.252.15.208/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
