---
# fabric variables for FINANCE

fabric_name: FINANCE_FABRIC
pod_name: FINANCE
site_number: 9
############################################################################
#           Common VLANs used in port profiles                             #
############################################################################
camera_vlan: 72
user_vlan: 32
voice_vlan: 132
printer_vlan: 52
wap_vlan: 62

mgmt_gateway: 10.252.15.1

############################################################################
#           Remove everything below after runnning in prod                 #
############################################################################

#daemon_terminattr:
#  cvaddrs:
#    - apiserver.arista.io:443
#  cvauth:
#    method: "token-secure"
#    token_file: "/mnt/flash/cv-onboarding-token"
#  cvvrf: MGMT
#  disable_aaa: true
#  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
#  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

aaa_authentication:
  login:
    default: local
    console: local

aaa_authorization:
  exec:
    default: local
