---

fabric_name: BACKBONE_FABRIC
pod_name: BACKBONE
mgmt_gateway: 172.16.1.1
site_number: 2
voice_vlan: 52
user_vlan: 152

############################################################################
#           Remove everything below after runnning in prod                 #
############################################################################

#daemon_terminattr:
#  cvaddrs:
#    - apiserver.arista.io:443
#  cvauth:
#    method: "token-secure"
#    token_file: "/mnt/flash/cv-onboarding-token"
#  cvvrf: MGMT
#  disable_aaa: true
#  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
#  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

aaa_authentication:
  login:
    default: local
    console: local

aaa_authorization:
  exec:
    default: local
