---
type: spine

switchport_default:
  mode: "routed"

monitor_connectivity:
  shutdown: false
  interval: 5
  hosts:
    - name: AWS-East-1
      ip: 50.17.255.254
    - name: Google
      ip: 8.8.8.8
      url: http://www.google.com
    - name: OpenDNS
      ip: 208.67.222.222
